=pod

=head1 NAME

aa-audit - set a AppArmor security profile to I<audit> mode.

=head1 SYNOPSIS

B<aa-audit I<E<lt>executableE<gt>> [I<E<lt>executableE<gt>> ...]>

=head1 DESCRIPTION

B<aa-audit> is used to set the audit mode for one or more profiles to audit.
In this mode security policy is enforced and all access (successes and failures) are logged to the system log.

=head1 BUGS

If you find any bugs, please report them at
L<https://bugs.launchpad.net/apparmor/+filebug>.

=head1 SEE ALSO

apparmor(7), apparmor.d(5), aa-enforce(1), aa-complain(1), aa-disable(1),
aa_change_hat(2), and L<http://wiki.apparmor.net>.

=cut
