#!/bin/sh

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "you need specified arguements"
    exit
fi    

ACTION=$1
TUN_IDX=$2
ONDEMAND_PID="/var/run/l2tpc-ondemand-$TUN_IDX.pid"
. /usr/bin/l2tpc-header

start_ondemand()
{
    addr=`get_csid_addr $CSID_C_L2TP_CLI_ROUTE $TUN_IDX`
    ROUTEING="`rdcsman $addr str`"
    if [ "$ROUTEING" == "" ]; then
        ROUTEING="0.0.0.0/0"
    fi

    if [ -z "`ps | grep "l2tp-ondemand -sub $ROUTEING -tun $TUN_IDX" | grep -v grep`" ]; then
        echo "l2tp-ondemand -sub $ROUTEING -tun $TUN_IDX"
        l2tp-ondemand -sub $ROUTEING -tun $TUN_IDX &
    fi
}

stop_ondemand()
{
    if [ -f $ONDEMAND_PID ]; then
        kill `cat $ONDEMAND_PID` > /dev/null 2>&1
    fi
    
#   pslist=`ps | grep l2tp-ondemand | grep "tun $TUN_IDX" `
#   if [ -z "$pslist" ]; then 
#       return
#   fi  
#
#   for i in $pslist
#   do 
#       pid=`echo $i` 
#       break 
#   done
#   kill -9 $pid >/dev/null 2>&1    
}

main()
{
    case "$ACTION" in
    restart)
        stop_ondemand
        start_ondemand
        ;;  

    start)
        start_ondemand
        ;;

    stop)
        stop_ondemand
        ;;	        
    *)
        exit 1
    esac   
}

#
# Main
#
main
