#!/bin/ash
# /usr/etc/profile
export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/bin/scripts:/mydlink
export LD_LIBRARY_PATH=/ram/lib:/lib:/usr/lib/iptables:/mydlink

alias d='ls'
alias dir='ls -al'

[ -e /etc/profile ] && sh /etc/profile

