#!/bin/sh

if [ -n $1 ] ; then
    MULTIWAN=$1
else
    MULTIWAN=
fi

CONFIG=/etc/ppp/pppoe.conf
if [ ! -f "$CONFIG" -o ! -r "$CONFIG" ] ; then
    echo "$0: Cannot read configuration file '$CONFIG'" >& 2
    exit 1
fi

export CONFIG
. $CONFIG

. /usr/bin/scriptlib

PIDFILE_START="$PIDFILE.start"
PIDFILE_CONNECT="$PIDFILE.connect"

if [ -z $MULTIWAN ] ; then
	PIDFILE_PPPD="/var/run/ppp-pppoe.pid"
else
	PIDFILE_PPPD="/var/run/ppp-pppoe$MULTIWAN.pid"
fi

# Backward config file compatibility
if test "$DEMAND" = "" ; then
	DEMAND=no
fi

# Ignore SIGTERM
trap "" 15

# Check for pidfile
if [ -r "$PIDFILE_CONNECT" ] ; then
    # Check if still running
    PID=`cat $PIDFILE_CONNECT`
    kill -0 $PID > /dev/null 2>&1
    if [ $? != 0 ] ; then
		echo "$0: The pppoe-connect script (PID $PID) appears to have died"
	else
		# Kill pppoe-connect
	    echo "Killing pppoe-connect ($PID)"
	    kill $PID > /dev/null 2>&1
    fi
fi

# Kill pppd, which should in turn kill pppoe
if [ -r "$PIDFILE_PPPD" ] ; then
    sl_get_ppp_PID_IFname $PIDFILE_PPPD PPPD_PID PPPD_IF
    echo "Killing pppd ($PPPD_PID)"
    kill $PPPD_PID > /dev/null 2>&1 || exit 1
fi	

# Kill pppoe-start
if [ -r $PIDFILE_START ] ; then
    PIDS=`cat $PIDFILE_START`
    echo "Killing pppoe-start ($PIDS)"
    kill -0 $PIDS > /dev/null 2>&1
    if [ $? = 0 ] ; then
		kill $PIDS > /dev/null 2>&1
    fi
fi

if [ -r "$PIDFILE_CONNECT" ] ; then
    # Kill pppoe-connect
    echo "Killing pppoe-connect ($PID)"
    kill -9 $PID > /dev/null 2>&1
fi


# Kill pppd again, in case it's still hanging around
if [ -r "$PIDFILE_PPPD" ] ; then
    sl_get_ppp_PID_IFname $PIDFILE_PPPD PPPD_PID PPPD_IF
    echo "Killing pppd ($PPPD_PID)"
    kill -9 $PPPD_PID > /dev/null 2>&1 
fi

rm -f "$PIDFILE_START" "$PIDFILE_CONNECT" "$PIDFILE_PPPD"
exit 0
