/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef STATUSWIRELESSSTATUS_H
#define STATUSWIRELESSSTATUS_H

/* function declarations */
void init_StatusWirelessStatus(void);
FindVarMethod var_StatusWirelessStatus;

extern     WriteMethod write_Basic1;
extern     WriteMethod write_Basic2;
extern     WriteMethod write_Basic3;
extern     WriteMethod write_Basic4;

#endif /* STATUSWIRELESSSTATUS_H */
